wp

diff --git a/bin/werf_handler b/bin/werf_handler
--- a/bin/werf_handler
+++ b/bin/werf_handler
@@ -8,13 +8,26 @@ done
 
 ### Get vault token
 JWT=`cat /var/run/secrets/kubernetes.io/serviceaccount/token`
+retVal=$?
+if [ $retVal -ne 0 ]; then
+    echo "Cannot read jwt token!"; exit 1;
+fi
+
 VAULT_TOKEN=`curl -s -k --request POST \
   --data '{"jwt": "'"${JWT}"'", "role": "'"${VAULT_AUTH_DEPLOY_ROLE}"'"}' \
-  ${VAULT_ADDR}/v1/auth/${VAULT_AUTH_METHOD}/login | jq -r '.auth.client_token'`
+  ${VAULT_ADDR}/v1/auth/${VAULT_AUTH_METHOD}/login | jq -e -r '.auth.client_token' 2>/dev/null`
+retVal=$?
+if [ $retVal -ne 0 ]; then
+    echo "Cannot get vault token!"; exit 1;
+fi
 
 ### Get deploy secrets
 SECRETS=`curl -s -H "X-Vault-Request: true" -H "X-Vault-Token: ${VAULT_TOKEN}" \
-  ${VAULT_ADDR}/v1/${VAULT_TENANT}/data/infra/deploy/${DEPLOY_SECRET}/cd | jq -r '.data.data | to_entries | map(.key + "=" + .value) | .[]'`
+  ${VAULT_ADDR}/v1/${VAULT_TENANT}/data/infra/deploy/${DEPLOY_SECRET}/cd | jq -e -r '.data.data | to_entries | map(.key + "=" + .value) | .[]' 2>/dev/null`
+retVal=$?
+if [ $retVal -ne 0 ]; then
+    echo "Cannot get vault secrets!"; exit 1;
+fi
 
 ### Set env vars from deploy secret
 for row in $(echo "${SECRETS}"); do
